"""Implemented session and seats for movies

Revision ID: a10fb3020e43
Revises: 6c6b20411d15
Create Date: 2026-02-15 03:47:33.711449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'a10fb3020e43'
down_revision: Union[str, Sequence[str], None] = '6c6b20411d15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cinema_rooms',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('total_seats', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('seats',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cinema_room_id', sa.String(), nullable=False),
    sa.Column('row', sa.String(length=1), nullable=False),
    sa.Column('column', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_aisle', sa.Boolean(), nullable=False),
    sa.Column('is_accessible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cinema_room_id'], ['cinema_rooms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cinema_room_id', 'row', 'column', name='uq_cinema_room_seat')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('movie_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('cinema_room_id', sa.String(), nullable=False),
    sa.Column('session_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cinema_room_id'], ['cinema_rooms.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seat_reservations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('seat_id', sa.String(), nullable=False),
    sa.Column('status', postgresql.ENUM('free', 'on_hold', 'confirmed', 'expired', name='seatstatus', create_type=False), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'seat_id', name='uq_session_seat_reservation')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seat_reservations')
    op.drop_table('sessions')
    op.drop_table('seats')
    op.drop_table('cinema_rooms')
    # ### end Alembic commands ###
